spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        driver-class-name: org.h2.Driver
        password: 
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
        username: sa
        generate-unique-name: false
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        database: h2
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                show-sql: true
        hibernate:
            naming:
                physical-strategy: com.musinsa.pointapiserver.util.UppercaseSnakePhysicalNamingStrategy
            ddl-auto: create-drop

logging:
  level:
    root: info
    org:
      hibernate:
        type:
          SQL: debug
          descriptor:
            sql:
              BasicBinder: trace
    com:
      musinsa: debug
